### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted

### ISSUE THREAD

**Issue by Manawyrm** [jrspruitt/ubi_reader#2]
Hi! I'm currently trying to use your software under archlinux, getting this error message, regardless of the input file. 

using Python 2.7.11 (default, Dec  6 2015, 15:43:46). 

```
[tobias@tobias-arch docsis2_w239th1]$ ubireader_utils_info -r chip1.bin 
Traceback (most recent call last):
  File "/usr/bin/ubireader_utils_info", line 4, in <module>
    __import__('pkg_resources').run_script('ubi-reader==0.4', 'ubireader_utils_info')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1677, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/ubi_reader-0.4-py2.7.egg/EGG-INFO/scripts/ubireader_utils_info", line 265, in <module>
    
  File "build/bdist.linux-x86_64/egg/ubireader/utils.py", line 62, in guess_filetype
TypeError: 'NoneType' object cannot be interpreted as an index
```

Any ideas? 

Best regards,
Tobias

**Comment by jrspruitt** [comment]
Hi Tobias,
Best I can tell chip1.bin is not a UBI or UBIFS image, that is why it
throws the error, it can't determine them. It could be they really are, but
the manufacture has changed the magic string used to determine the image
type. It would take some investigation to determine if it can be worked
around or not. If you can link to it the image file, I can check it out if
you like. Also thanks for pointing this out, it should fail more gracefully
I'll work on a fix for that too.
Thanks,
-Jason
