### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by shavenne** [jrspruitt/ubi_reader#49]
Hi,

I'm trying to extract the data out of an NAND dump I've made from a FTTH ONT.
It seems it has UBI in it but I can't get to extract it.
It may be something special about this UBI because I also don't get it running on any other way like putting the dump into mtd/nandsim and use ubiattach (getting "unsupported on-flash UBI format" then).

That's what I get with ubireader:
```
$ ubireader_display_info CleanDump.bin
Traceback (most recent call last):
  File "/usr/local/bin/ubireader_display_info", line 4, in <module>
    __import__('pkg_resources').run_script('ubi-reader==0.7.1', 'ubireader_display_info')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ubi_reader-0.7.1-py2.7.egg/EGG-INFO/scripts/ubireader_display_info", line 132, in <module>

  File "build/bdist.linux-x86_64/egg/ubireader/ubi/__init__.py", line 166, in __init__
  File "build/bdist.linux-x86_64/egg/ubireader/ubi/image.py", line 31, in __init__
TypeError: 'int' object is not iterable
```

That's of binwalk finds out of this dump:
```
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
168116        0x290B4         AES Inverse S-Box
168372        0x291B4         AES S-Box
169716        0x296F4         SHA256 hash constants, little endian
169972        0x297F4         CRC32 polynomial table, little endian
303284        0x4A0B4         AES Inverse S-Box
303540        0x4A1B4         AES S-Box
304884        0x4A6F4         SHA256 hash constants, little endian
305140        0x4A7F4         CRC32 polynomial table, little endian
434356        0x6A0B4         AES Inverse S-Box
434612        0x6A1B4         AES S-Box
435956        0x6A6F4         SHA256 hash constants, little endian
436212        0x6A7F4         CRC32 polynomial table, little endian
567476        0x8A8B4         AES Inverse S-Box
567732        0x8A9B4         AES S-Box
569076        0x8AEF4         SHA256 hash constants, little endian
569332        0x8AFF4         CRC32 polynomial table, little endian
698548        0xAA8B4         AES Inverse S-Box
698804        0xAA9B4         AES S-Box
700148        0xAAEF4         SHA256 hash constants, little endian
700404        0xAAFF4         CRC32 polynomial table, little endian
831668        0xCB0B4         AES Inverse S-Box
831924        0xCB1B4         AES S-Box
833268        0xCB6F4         SHA256 hash constants, little endian
833524        0xCB7F4         CRC32 polynomial table, little endian
1703866       0x19FFBA        Sercomm firmware signature, version control: 0, download control: 1, hardware ID: "DHP", hardware version: 0x4100, firmware version: 0x1, starting code segment: 0x0, code size: 0x7300
2097152       0x200000        UBI erase count header, version: 1, EC: 0x0, VID header offset: 0x800, data offset: 0x1000
5898170       0x59FFBA        Sercomm firmware signature, version control: 0, download control: 1, hardware ID: "DHP", hardware version: 0x4100, firmware version: 0x0, starting code segment: 0x0, code size: 0x7300
10092474      0x99FFBA        Sercomm firmware signature, version control: 0, download control: 1, hardware ID: "DHP", hardware version: 0x4100, firmware version: 0x0, starting code segment: 0x0, code size: 0x7300
12845056      0xC40000        JFFS2 filesystem, little endian
101318656     0x60A0000       JFFS2 filesystem, little endian
```

When I extract that JFFS2 filesystems they're kinda broken too. It mounts and I can see some files but they can't be all of them and I'm getting CRCs errors in dmesg then.
I've thought the dump is maybe broken but my dump programmer is verifying it fine and I always get the same checksum everytime I make a dump from the original NAND.

Any idea?

This is the full 128MByte dump (with OOB/spare data removed):
https://cloud.mimimiii.net/index.php/s/zNf3cQYqdNsz9tt

Best regards
Sven / shavenne

**Comment by jrspruitt** [comment]
Hi Sven,

Looks like the issue is that there is a copy of the UBI blocks later in the dump, so ubi_reader gets confused and tries to use all the data it found. To isolate them, you need to use the -n and -s flags, end cuts out the second version, and -s cuts out the first version
```
# Get first version of UBI data.
ubireader_display_info -n 6291456 F59L1G81MB\@TSOP48_wOut_OOB.bin

# Rename ubi-root/ created with first command. So it doesn't get written over.
# Get second version of UBI data.
ubireader_display_info -s 6291456 F59L1G81MB\@TSOP48_wOut_OOB.bin
```
6291456 is the data offset of the bin file where the second version starts. I figured out the offset using verbose to find the layout blocks, which shows the needed offset. Thanks for submitting this, it's not very common, I'll see if I can implement a more graceful/informative way to deal with this issue.

-Jason

**Comment by shavenne** [comment]
Thank you very much! I was able to extract way more files now.
It still seems somehow broken (I can't extract anything useful out of the first ubi image/ubifs for example. The image seems too small) but I have to say I have no experience at all in doing something like that. First time trying to modify a firmware. Some days ago I even had no idea how to dump a nand directly. 😄 
Maybe there's something proprietary going on and that's the reason why it seems so broken!?

My main goal is to change the gpon serial number (I may have what I need for that now) and maybe get some kind of terminal. I've found a serial header but except seeing the boot log I can't do anything with that at this moment. I don't get any prompt or something.

**Comment by jrspruitt** [comment]
Hi Sven,

Glad you got some more out of it. ubi_reader just assumes the filesystem is ubifs and uses that extension, it could be a different filesystem. The images I opened in a hex editor, I did not recognize what they were. Also a chance it's just raw data as this didn't look like Linux or a Kernel, just a single app that is run.

Good look on your project, I think this is how a lot of people started, they want to change something, and then have to learn a whole bunch of new things ;)

-Jason
